# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='skype',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
