# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-20 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skype',
            field=models.CharField(default='skype', max_length=256),
            preserve_default=False,
        ),
    ]
