# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170525_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(null=True, to='courses.Course'),
        ),
    ]
