# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170520_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name='date_published'),
        ),
    ]
