"""
Django settings for pybursa project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1b_fjyt!(&yw^y^xl@w-9-)&@ho^l7m6=j_#y^)drnx4a&0*83'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


WSGI_APPLICATION = 'pybursa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


ADMINS = (('Ponomarenko Valerii', 'ponomarenko.valerij@gmail.com'), ('Valerii Ponomarenko', 'panval@mail.ru'))

EMAIL_HOST = 'smtp.sendgrid.net'

EMAIL_PORT = '587'

EMAIL_SUBJECT_PREFIX = '[PyBursa]'

SERVER_EMAIL = 'ValeriiPonomarenko.sendgrid'

EMAIL_HOST_USER = 'ValeriiPonomarenko.sendgrid'

EMAIL_HOST_PASSWORD = 'send9379992'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'main': {
            'format': '%(levelname)s %(asctime)s %(module)s %(funcName)s %(message)s',
            'datefmt': "%Y-%m-%d %H:%M:%S",
        },
        'main1': {
            'format': '%(levelname)s %(message)s'
        },
    },

    'loggers': {
        'courses': {
            'handlers': ['file'],
            'level': 'DEBUG'
        },
        'students': {
            'handlers': ['file1'],
            'level': 'WARNING'
        },
    },

    'handlers': {
            'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'courses_logger.log'),
            'formatter': 'main1'
        },
        'file1': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'students_logger.log'),
            'formatter': 'main'
        },
    },
}