"""
Django settings for pybursa project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l3raql1^xo$2v9m0k#yc@h0zlpi^_+*b7qn1id4@um67(jvvp)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


ADMINS = (('test','test_misha@yopmail.com'),('admin','admin_misha@yopmail.com'))

EMAIL_HOST = 'smtp.sendgrid.net'

EMAIL_PORT = '587'

EMAIL_SUBJECT_PREFIX = '[PyBursa]'

SERVER_EMAIL = 'pyBursa'

EMAIL_HOST_USER = 'misha.sendgrid'

EMAIL_HOST_PASSWORD = 'misha_test123'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'main': {
            'format': '%(levelname)s %(asctime)s %(module)s %(funcName)s %(message)s',
            'datefmt': "%Y-%m-%d %H:%M:%S",
        },
        'main1': {
            'format': '%(levelname)s %(message)s'
        },
    },

    'loggers': {
        'courses': {
            'handlers': ['file1'],
            'level': 'DEBUG'
        },
        'students': {
            'handlers': ['file2'],
            'level': 'WARNING'
        },
    },

    'handlers': {
        'file1': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'courses_logger.log'),
            'formatter': 'main1'
        },
        'file2': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'students_logger.log'),
            'formatter': 'main'
        },
    },
}
