# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_auto_20180212_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
