# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-13 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_auto_20180212_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
