# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Подробное описание'),
        ),
    ]
