# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='orser',
            new_name='order',
        ),
    ]
