# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
        ('courses', '0004_auto_20170526_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assisttant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_courses', to='coaches.Coach', verbose_name='Ассистент'),
        ),
        migrations.AddField(
            model_name='course',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaches_courses', to='coaches.Coach', verbose_name='Тренер'),
        ),
    ]
