# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170525_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coach_courses', to='coaches.Coach'),
            preserve_default=False,
        ),
    ]
