# Generated by Django 2.2.5 on 2019-11-17 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(auto_now=True, verbose_name='краткое описание')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30, verbose_name='пол')),
                ('phone', models.CharField(max_length=30, verbose_name='телефон')),
                ('adress', models.CharField(max_length=30, verbose_name='адресс')),
                ('skype', models.CharField(max_length=30, verbose_name='skype')),
                ('description', models.TextField(max_length=30, verbose_name='описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
