# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-17 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='ate_of_birth',
            new_name='date_of_birth',
        ),
    ]
