# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
