# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
    ]
